---
title: "Task 1"
author: "Max Settineri"
date: "2023-02-28"
output: 
  html_document:
    code_folding: hide
    toc: yes
---

## Introduction



**Data** compiled and provided by @zander_venter on Kaggle, described as: “This data is all acquired through Google Earth Engine (https://earthengine.google.com/) where publicly available remote sensing datasets have been uploaded...Most of the data is derived by calculating the mean for each country at a reduction scale of about 10km.”

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(janitor)
library(here)
library(ggfortify) 
library(patchwork)
library(gghighlight)
library(lubridate)
library(plotly) 
```

## PCA

```{r}
## reading in the data
environmental <- read_csv(here('data/world_env_vars.csv')) %>% 
  drop_na() %>% ## dropping rows with NA values
  clean_names()

environmental_pca <- environmental_clean %>% 
  scale() %>% ## scaling data to one standard deviation
  prcomp() ## running the PCA

```

```{r}
autoplot(environmental_pca,
     	data = environmental,
     	loadings = TRUE,
     	colour = 'cloudiness',
     	loadings.label = TRUE,
     	loadings.colour = "black",
     	loadings.label.colour = "black",
     	loadings.label.vjust = -0.5) +
  scale_color_gradient(low = 'goldenrod', high = 'steelblue4') +
  theme_minimal()
```

**Figure 1:** ...

## Screeplot

```{r}
sd_vec <- environmental_pca$sdev ## extracting sd for each pc
var_vec <- sd_vec^2 ## calculating variance of each pc by squaring the sd of each pc
pc_names <- colnames(environmental_pca$rotation) ## pulling names of each pc

## creating data frame with the variance of each pc
pct_expl_df <- data.frame(v = var_vec,
                          pct_v = var_vec / sum(var_vec),
                          pc = fct_inorder(pc_names)) %>% 
  mutate(pct_lbl = paste0(round(pct_v * 100, 1), '%'))

## creating screeplot
ggplot(pct_expl_df, aes(x = pc, y = v)) + ## mapping pc to the x axis and variance to the y
  geom_col() + 
  geom_text(aes(label = pct_lbl), vjust = 0, nudge_y = .002) +
  labs(x = 'Principal component', y = 'Variance explained')
```

**Figure 2:** ...

## Summary